import type { GeneratedArtifacts, PackageReference, WingetOptions } from '../types'
import { DEFAULT_WINGET_OPTIONS, WINGET_OPTION_FLAGS } from '../types'
import { assertValidPackageId } from './package-id'

const OPTION_ORDER = [
  'acceptSourceAgreements',
  'disableInteractivity',
  'force',
  'ignoreSecurityHash',
  'silent',
  'verbose',
] as const satisfies ReadonlyArray<keyof WingetOptions>

const WINDOWS_NEWLINE = '\r\n'

function packageIds(packages: readonly PackageReference[]): string[] {
  const ids = packages.map(({ id }) => id)
  ids.forEach(assertValidPackageId)
  return ids
}

export function getEnabledWingetFlags(options: Readonly<WingetOptions>): string[] {
  return OPTION_ORDER.filter((key) => options[key]).map((key) => WINGET_OPTION_FLAGS[key])
}

/** Generate one exact-ID install invocation, primarily for scripts. */
export function generatePackageInstallCommand(
  packageId: string,
  options: Readonly<WingetOptions> = DEFAULT_WINGET_OPTIONS,
): string {
  assertValidPackageId(packageId)
  const flags = getEnabledWingetFlags(options)
  return ['winget', 'install', '--id', packageId, '--exact', ...flags].join(' ')
}

/**
 * Generate the modern WinGet multi-package syntax. Package IDs remain in the
 * exact order provided by selection state.
 */
export function generateWingetCommand(
  packages: readonly PackageReference[],
  options: Readonly<WingetOptions> = DEFAULT_WINGET_OPTIONS,
): string {
  const ids = packageIds(packages)
  if (ids.length === 0) return ''

  return ['winget', 'install', ...ids, ...getEnabledWingetFlags(options)].join(' ')
}

export function generatePowerShellScript(
  packages: readonly PackageReference[],
  options: Readonly<WingetOptions> = DEFAULT_WINGET_OPTIONS,
): string {
  const ids = packageIds(packages)
  if (ids.length === 0) return ''

  const flags = getEnabledWingetFlags(options).join(' ')
  const wingetArguments = ['install', '--id', '$packageId', '--exact', flags]
    .filter(Boolean)
    .join(' ')

  const lines = [
    '# Generated by WingetWebUI',
    "$ErrorActionPreference = 'Stop'",
    '',
    '$packages = @(',
    ...ids.map((id) => `    '${id}'`),
    ')',
    '',
    'foreach ($packageId in $packages) {',
    '    Write-Host "Installing $packageId..."',
    `    & winget ${wingetArguments}`,
    '    if ($LASTEXITCODE -ne 0) {',
    '        throw "WinGet failed to install $packageId (exit code $LASTEXITCODE)."',
    '    }',
    '}',
    '',
    "Write-Host 'All selected packages were installed successfully.'",
    '',
  ]

  return lines.join(WINDOWS_NEWLINE)
}

export function generateBatchScript(
  packages: readonly PackageReference[],
  options: Readonly<WingetOptions> = DEFAULT_WINGET_OPTIONS,
): string {
  const ids = packageIds(packages)
  if (ids.length === 0) return ''

  const flags = getEnabledWingetFlags(options).join(' ')
  const installCommand = ['winget install --id "%~1" --exact', flags].filter(Boolean).join(' ')

  const calls = ids.flatMap((id) => [`call :install "${id}"`, 'if errorlevel 1 exit /b 1'])

  const lines = [
    '@echo off',
    'setlocal',
    'rem Generated by WingetWebUI',
    '',
    ...calls,
    '',
    'echo All selected packages were installed successfully.',
    'exit /b 0',
    '',
    ':install',
    'echo Installing %~1...',
    installCommand,
    'if errorlevel 1 (',
    '    echo Failed to install %~1.',
    '    exit /b 1',
    ')',
    'exit /b 0',
    '',
  ]

  return lines.join(WINDOWS_NEWLINE)
}

export function generateArtifacts(
  packages: readonly PackageReference[],
  options: Readonly<WingetOptions> = DEFAULT_WINGET_OPTIONS,
): GeneratedArtifacts {
  return {
    command: generateWingetCommand(packages, options),
    powershell: generatePowerShellScript(packages, options),
    batch: generateBatchScript(packages, options),
  }
}
